### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by ImMaddd** [ImMaddd/ABB-Trading#5]
firebase : File C:\Users\berda\AppData\Roaming\npm\firebase.ps1 cannot be loaded. The file
C:\Users\berda\AppData\Roaming\npm\firebase.ps1 is not digitally signed. You cannot run this script on the current system. For
more information about running scripts and setting execution policy, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ firebase
+ ~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by HashJProgramming** [comment]
## Terminal

```
Set-ExecutionPolicy RemoteSigned
```
